pipeline {
    agent any  
    stages {
        stage('Checkout') {
            steps {
                ws(dir:"${JENKINS_HOME}/jobs/${JOB_NAME}/builds/${BUILD_ID}/src/time-logger") {
                    git(
                        url: 'https://github.com/fr0stylo/STPP.git',
                        branch: "master"
                    )    
                }
            }
            
        }
        stage('Config build'){
            steps {
                ws("${JENKINS_HOME}/jobs/${JOB_NAME}/builds/${BUILD_ID}/src/time-logger") {
                    withEnv(["GOPATH=${JENKINS_HOME}/jobs/${JOB_NAME}/builds/${BUILD_ID}"]) {
                            sh "go get -v ./cmd/config"
                            sh "cd build && CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -v ../cmd/config"
                    }
                }
            }
        }
        stage('Projects build'){
            steps {
                ws("${JENKINS_HOME}/jobs/${JOB_NAME}/builds/${BUILD_ID}/src/time-logger") {
                    withEnv(["GOPATH=${JENKINS_HOME}/jobs/${JOB_NAME}/builds/${BUILD_ID}"]) {
                        sh "go get -v ./cmd/projects"
                        sh "cd build && CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -v ../cmd/projects"
                    }
                }
            }
            
        }

        stage('Tasks build'){
            steps {
                    ws("${JENKINS_HOME}/jobs/${JOB_NAME}/builds/${BUILD_ID}/src/time-logger") {
                    withEnv(["GOPATH=${JENKINS_HOME}/jobs/${JOB_NAME}/builds/${BUILD_ID}"]) {
                        sh "go get -v ./cmd/tasks"
                        sh "cd build && CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -v ../cmd/tasks"
                    }
                }
            }
        }

        stage('Time Entries build'){
            steps {
                ws("${JENKINS_HOME}/jobs/${JOB_NAME}/builds/${BUILD_ID}/src/time-logger") {
                    withEnv(["GOPATH=${JENKINS_HOME}/jobs/${JOB_NAME}/builds/${BUILD_ID}"]) {
                        sh "go get -v ./cmd/time-entries"
                        sh "cd build && CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -v ../cmd/time-entries"
                    }
                }
                
            }
        }
        stage('Api Gateway build'){
            steps {
                ws("${JENKINS_HOME}/jobs/${JOB_NAME}/builds/${BUILD_ID}/src/time-logger/api-gateway"){
                    sh "npm install"
                    sh "npm run build"
                }
            }
        }
        stage('Docker build'){
            steps {
               ws("${JENKINS_HOME}/jobs/${JOB_NAME}/builds/${BUILD_ID}/src/time-logger"){
                   sh "docker build -t config -f ./scripts/docker/config/Dockerfile ."
                   sh "docker tag config 159.89.31.121:5000/zm/congfig:0.0.${BUILD_ID}"
                   sh "docker push config"
                }
            }
        }
    } 
   
}
