pipeline {
    agent any  
    stages {
        stage('Checkout') {
            steps {
                ws(dir:"${JENKINS_HOME}/jobs/${JOB_NAME}/builds/${BUILD_ID}/src/time-logger") {
                    git(
                        url: 'https://github.com/fr0stylo/STPP.git',
                        branch: "master"
                    )    
                }
            }
            
        }
        stage('Config build'){
            steps {
                ws("${JENKINS_HOME}/jobs/${JOB_NAME}/builds/${BUILD_ID}/src/time-logger") {
                    withEnv(["GOPATH=${JENKINS_HOME}/jobs/${JOB_NAME}/builds/${BUILD_ID}"]) {
                            sh "go get -v ./cmd/config"
                            sh "cd build && CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -v ../cmd/config"
                    }
                }
            }
        }
        stage('Projects build'){
            steps {
                ws("${JENKINS_HOME}/jobs/${JOB_NAME}/builds/${BUILD_ID}/src/time-logger") {
                    withEnv(["GOPATH=${JENKINS_HOME}/jobs/${JOB_NAME}/builds/${BUILD_ID}"]) {
                        sh "go get -v ./cmd/projects"
                        sh "cd build && CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -v ../cmd/projects"
                    }
                }
            }
            
        }

        stage('Tasks build'){
            steps {
                    ws("${JENKINS_HOME}/jobs/${JOB_NAME}/builds/${BUILD_ID}/src/time-logger") {
                    withEnv(["GOPATH=${JENKINS_HOME}/jobs/${JOB_NAME}/builds/${BUILD_ID}"]) {
                        sh "go get -v ./cmd/tasks"
                        sh "cd build && CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -v ../cmd/tasks"
                    }
                }
            }
        }

        stage('Time Entries build'){
            steps {
                ws("${JENKINS_HOME}/jobs/${JOB_NAME}/builds/${BUILD_ID}/src/time-logger") {
                    withEnv(["GOPATH=${JENKINS_HOME}/jobs/${JOB_NAME}/builds/${BUILD_ID}"]) {
                        sh "go get -v ./cmd/time-entries"
                        sh "cd build && CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -v ../cmd/time-entries"
                    }
                }
                
            }
        }

        stage('Api Gateway build'){
            steps {
                ws("${JENKINS_HOME}/jobs/${JOB_NAME}/builds/${BUILD_ID}/src/time-logger/api-gateway"){
                    sh "npm install"
                    sh "npm run build"
                }
            }
        }
        stage('Docker builds') {
            parallel {
                stage('Config docker build'){
                    steps {
                    ws("${JENKINS_HOME}/jobs/${JOB_NAME}/builds/${BUILD_ID}/src/time-logger"){
                        sh "docker build -t config -f ./scripts/docker/config/Dockerfile ."
                        sh "docker tag config 159.89.31.121:5000/zm/config:0.0.${BUILD_ID}"
                        sh "docker push 159.89.31.121:5000/zm/config:0.0.${BUILD_ID}"
                        }
                    }
                }

                stage('Projects docker build'){
                    steps {
                    ws("${JENKINS_HOME}/jobs/${JOB_NAME}/builds/${BUILD_ID}/src/time-logger"){
                        sh "docker build -t projects -f ./scripts/docker/projects/Dockerfile ."
                        sh "docker tag projects 159.89.31.121:5000/zm/projects:0.0.${BUILD_ID}"
                        sh "docker push 159.89.31.121:5000/zm/projects:0.0.${BUILD_ID}"
                        }
                    }
                }
                
                stage('Tasks docker build'){
                    steps {
                    ws("${JENKINS_HOME}/jobs/${JOB_NAME}/builds/${BUILD_ID}/src/time-logger"){
                        sh "docker build -t tasks -f ./scripts/docker/tasks/Dockerfile ."
                        sh "docker tag tasks 159.89.31.121:5000/zm/tasks:0.0.${BUILD_ID}"
                        sh "docker push 159.89.31.121:5000/zm/tasks:0.0.${BUILD_ID}"
                        }
                    }
                }

                stage('time-entries docker build'){
                    steps {
                    ws("${JENKINS_HOME}/jobs/${JOB_NAME}/builds/${BUILD_ID}/src/time-logger"){
                        sh "docker build -t time-entries -f ./scripts/docker/time-entries/Dockerfile ."
                        sh "docker tag time-entries 159.89.31.121:5000/zm/time-entries:0.0.${BUILD_ID}"
                        sh "docker push 159.89.31.121:5000/zm/time-entries:0.0.${BUILD_ID}"
                        }
                    }
                }

                stage('Api-gateway docker build'){
                    steps {
                    ws("${JENKINS_HOME}/jobs/${JOB_NAME}/builds/${BUILD_ID}/src/time-logger"){
                        sh "docker build -t api-gateway -f ./scripts/docker/api-gateway/Dockerfile ."
                        sh "docker tag api-gateway 159.89.31.121:5000/zm/api-gateway:0.0.${BUILD_ID}"
                        sh "docker push 159.89.31.121:5000/zm/api-gateway:0.0.${BUILD_ID}"
                        }
                    }
                }
            }
        }
        
        stage('Cleanup') {
            steps {
                sh "docker images prune"
            }
        }
    } 
   
}
